id: ABB148A2D
title: 'Self-Arising Wisdom: Songtsen Gampo Guru Sādhana'
type: translation
pechas:
- IA97809F0
- I4758C477
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:08.941996
  last_modified_at: 2023-01-04 12:13:08.942000
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IA97809F0/BCB8: 458A
  I4758C477/1E3E: 458A
